repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        args: ['--config=./pyproject.toml']
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.289
    hooks:
      - id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [
          fastapi==0.99.1,
          sqlalchemy==2.0.17,
          typing-extensions==4.7.1
        ]
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v2.4.0'
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: [
            'build',
            'chore',
            'ci',
            'docs',
            'feat',
            'fix',
            'perf',
            'refactor',
            'revert',
            'style',
            'test'
        ]