[tool.mypy]
python_version = 3.11
warn_unused_configs = true
warn_return_any = true
disallow_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
show_error_context = true
pretty = true

[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
# Enable pycodestyle (`E`), Pyflakes (`F`), pycodestyle warnings (`W`),
# McCabe complexity (`C901`), pep8-naming (`N`), pydocstyle (`D`),
# pyupgrade (`UP`) and pylint (`PL`).
select = ["E", "F", "W", "C901", "N", "D", "UP", "PL"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}

# Same as Black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11.
target-version = "py311"

[tool.ruff.isort]
# Placeholder for future configuration.

[tool.ruff.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 10.
max-complexity = 10

[tool.ruff.pep8-naming]
# Placeholder for future configuration.

[tool.ruff.pydocstyle]
# Use Google-style docstrings.
convention = "google"

[tool.ruff.pylint]
# Placeholder for future configuration.

[tool.ruff.pyupgrade]
# Placeholder for future configuration.
